name: Photography By Anne Bussell
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74558
title: Photography By Anne Bussell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#ceb9e6'
    - '#61826c'
    - '#a78fb8'
    - '#9eca6d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
